config/routes.rb
Rails.application.routes.draw do

  
  	devise_for :users, :controllers => { registrations: 'registrations' }
  	resources :articles
	root 'pages#index'

	get 'pages/contact'

	get 'pages/about'

	resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	
belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates_presence_of  :name
	validates_presence_of  :email
	validates_presence_of  :message
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :articles 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

 def new
 	@contact = Contact.new
 end

 def create
 	@contact = Contact.new(contact_params)

	if @contact.save
		 redirect_to root_path
		 name = params[:contact][:name]
		 email = params[:contact][:email]
		 message = params[:contact][:message]
		 ContactMailer.contact_email(name, email, message).deliver
		 flash[:success] = "Thanks for reaching out, I'll be in touch soon."
	 
	else

	 		redirect_to pages_contact_path
	 		flash[:danger] = "Opps, there was a problem! Please fill out all the fields."
		end
	 end



 private

 def contact_params
 	params.require(:contact).permit(:name, :email, :message)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
  	@articles = Article.last(5)
  end

  def contact
  	@contact= Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

def sign_up_params
	params.require(:user).permit(
		:email, 
		:password, 
		:password_confirmation,
		:username,
		:firstname,
		:lastname
		)
	end

def account_update_params
	params.require(:user).permit(
		:email, 
		:password, 
		:password_confirmation, 
		:current_password,
		:username,
		:firstname,
		:lastname
		)
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Created By</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.user.username %></td>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>
<p><object width="371" height="306"><param name="movie"
value="http://www.youtube.com/v/<%=params[:video_id]%>&au...
/><embed
src="http://www.youtube.com/v/<%=params[:video_id]%>&au...
type="application/x-shockwave-flash" width="371"
height="306"></embed></object></p>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created by:</strong>
  <%= @article.user.username %>
</p>



<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed">
	<div class="footer-right">
			<div>
				<p class="footer-right">
					<a href="https://www.facebook.com/dancesnitch"><i class="fa fa-facebook"></i></a>
					<a href="http://twitter.com/dancesnitch"><i class="fa fa-twitter"></i></a>
					<!--<a href="#"><i class="fa fa-linkedin"></i></a>-->
					<a href="http://github.com/dancesnitch"><i class="fa fa-github"></i></a>
				</p>
			</div>
		
			<p class="footer-right">
				<i class="devicon-ruby-plain colored"></i>
				<i class="devicon-rails-plain colored"></i>
				<i class="devicon-heroku-plain-wordmark colored"></i>
				<i class="devicon-html5-plain-wordmark colored"></i>
				<i class="devicon-css3-plain-wordmark colored"></i>
				<i class="devicon-bootstrap-plain-wordmark colored"></i>
				<i class="devicon-sass-original colored"></i>		
		
	</div>
		<div class="footer-left">
			<p class="footer-links">
			·
			<%= link_to "Contact Me", pages_contact_path, class: "page-scroll" %>
			·
			<%= link_to "About Me", pages_about_path, class: "page-scroll" %>
			·
			</p>
		<p class="footer-company-name">DanielJohn|Apps &copy; 2017 </p>
	</div>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-00000000-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DanielJohn | Apps", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <!--<li><a href="#">Link</a></li>-->
        
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <li><%=link_to "Contact Me", pages_contact_path if !current_user %></li>
        <li><%=link_to "About Me", pages_about_path if !current_user %></li>
        <li><%=link_to "Recent Articles", articles_path if current_user %></li>
        <li><%=link_to "Create an Article", new_article_path %></li>
        <% if !current_user %>
        <li><%=link_to "Sign Up", new_user_registration_path %></li>
        <li><%=link_to "Sign In", new_user_session_path %></li>
        
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <li><%=link_to "Edit My Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li> 
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />


    <title>DanielJohnApps</title>
    <%= csrf_meta_tags %>

    <!--Devicon Program Language Icons-->
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">


    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/navbar' %>
      <%= bootstrap_flash %>
  <div class="container">
	    <%= yield %>
	 </div>	
      <%= render 'layouts/foot' %>
  </body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-100364558-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pages/_mail.html.erb
<div class="row">
	 <div class="col-md-6 col-md-offset-3">
		 <div class="well">
			 <%= simple_form_for @contact do |f| %>
			 <%= f.input :name %>
			 <%= f.input :email %>
			 <%= f.input :message %>
			 <%= f.submit "Get in touch!", class: "btn btn-info" %>
			 <% end %>
		 </div>
	 </div>
</div>

app/views/pages/about.html.erb
    <!-- About Section -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                 <%= image_tag("https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/danieldrums.png", class: "img-thumbnail")%><!--img class="img-responsive" src="img/profile.png"--> <alt="">
               <div class="col-lg-8 col-lg-offset-2 text-center">
                  <div class="col-lg-12 text-center">
                              <h1>About Me</h1>
                              <hr class="star-light">
                  </div> 
                    <%= link_to "Contact Me", pages_contact_path, class: "fa fa-wechat", class: "btn btn-lg btn-outline" %>
              </div>
            </div>
        </div>    
   </header> 
   </br>
   <body>
              <div class="row" id="aboutme">
                <div class="bio">
                  <div class="col-lg-6  text-left">
                      <div class="col-lg-6 text-right" id="aboutlogo">
                          <h1>DESIGNS</h1><h1><strong>FORGED</strong></h1>
                          <h1><small><strong>WITH</strong></small>PASSION</h1>
                      </div>
                      <p>My name is Daniel John Byrne
                      I created this application to showcase some of my Ruby on Rails abilities. This website features a short portfolio and biography about myself and offers users a chance to contribute articles to this site. The articles will be found on the home page under "recent articles". To add, view and create artcles you must <a href="http://danieljohnportfolio.herokuapp.com/users/sign_up"><strong>Sign Up!</strong></p></a> 
                    
                      <h3>About Me:</h3>
                      <p>I am a Freelance Full Stack Ruby on Rails developer. I was introduced to Ruby on Rails in 2015. In addition to Ruby on Rails I have worked on various projects using the following:
                      </br>
                      <!-- Tools and Tech I use -->
                      <br>
                        <strong>                         
                            <div class="techlogo">
                                <p>
                                <i class="devicon-html5-plain colored">HTML5</i> 
                                <i class="devicon-css3-plain-wordmark colored">CSS3</i> 
                                <i class="devicon-jquery-plain colored">jQuery</i> 
                                <i class="devicon-javascript-plain">JavaScript</i>
                                </p> 
                                <p>
                                <i class="devicon-bootstrap-plain-wordmark">BootStrap</i>  
                                <i class="devicon-sass-original colored">Sass</i> 
                                <i class="devicon-heroku-plain-wordmark colored">HEROKU</i>  
                                <i class="devicon-github-plain">GitHub</i>
                                </p> 
                                <p>
                                <i class="devicon-wordpress-plain">WordPress</i> 
                                <i class="devicon-amazonwebservices-original colored">AWS</i> 
                                <i class="devicon-postgresql-plain colored">PgAdmin</i> 
                                <i class="devicon-chrome-plain colored">WebInspect</i>
                               </p> 
                                <p>
                                <i class="devicon-mysql-plain colored">MySql</i>
                                <i class="devicon-apple-original">OSX</i>
                                <i class="devicon-ubuntu-plain colored">Ubuntu</i>
                                <i class="devicon-photoshop-line">PhotoShop</i>
                                </p>
                                <p>
                                <i class="fa fa-cloud">Cloud9IDE</i>
                                <i class="devicon-ruby-plain colored">Ruby</i>
                                <i class="devicon-rails-plain colored">Rails</i>
                                </p>
                            </div>
                        </strong>
                      </br>
                      </p>

                      <p>In June 2014 two friends and I came up with an idea to create an E-Commerce store selling mens clothing and accessories, from there I decided if I'm going to enter the E-commerce world I should learn how to develop my own website and thats exactly what I did. By learning WordPress and minor PHP coding myself along with my partners were able to launch our very own E-commerce store. </p>

                </div>
              <div class="col-lg-5 text-left">
                      <p> Prior to web development I was a full time musician as well as a retail manager in Telecommunications. My passion for music started when I was 6 years of age. My father had his old drum set sitting in the attic. When I spotted them collecting dust I immediately asked "Hey Dad what are those?" From that point on I was non-stop music. At the age of 23, I attended college, graduating with an associates degree in Business Marketing Administration and jumped into sales and store management for Canada's number 1 telecommunication company Bell Mobility/Virgin Canada.
                      </p>

                      <p>My hobbies and interest include long hikes, camping, traveling, watching live music, redditing and enjoying some down time with my guitar. On occasion I can be found in-person at local meetups and coffee pubs throughout areas of Toronto, Canada, United Kingdom and Ireland working on various coding projects.</p>

                      <p>If you have a question(s) or would like to learn more about what I do, please feel free to contact me on here or by <a href="mailto:byrne.daniel87@gmail.com?Subject=Contact%20DanielJohnApps"target="_top">Email.</a></p><br/>

                      <p> Kind Regards, </p><br/>

                      <p>Daniel</p>
              </div>
            </div>
        </div>
</body>
 

app/views/pages/contact.html.erb
<div class="row">
	 <div class="col-md-12 text-center">
		 <h1>Contact Me</h1>
			 <p class="lead">Thank you for looking at my portfolio!</p>
			 <ul class="list-unstyled">
			 <li>If you have a question(s)</li>
			 <li>Drop me a line!</li>
			 </ul>
	 </div> 	
</div>

<%= render 'pages/mail' %>

app/views/pages/index.html.erb
 <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                    <%= image_tag("https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/dancesnitch.jpg", class: "img-circle")%><!--img class="img-responsive" src="img/profile.png"--> <alt="">
                    <div class="intro-text">
                        <h1 class="name">D.J.B Portfolio</h1>
                        <hr class="star-light">
                        <span class="skills" id="subtitle">Web Developer <br/>
                        Full Stack Programmer</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Portfolio Grid Section -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>My Portfolio</h2>
                    <hr class="star-primary">
                </div>
            </div>
                <div class="row">
                    <div class="col-sm-4 portfolio-item">
                        <a href="https://solucentinc.com" class="portfolio-link" data-toggle="modal">
                            <div class="caption">
                                <div class="container" width="100%">
                                    <img src="https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/solucent_shop.jpg" alt=" solucent_shop">
                                </div>
                            </div>
                            <%= image_tag("https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/solucent_home.jpg")%><!--img src="img/portfolio/game.png"--><class="img-responsive" alt="solucent_home">
                    </div>
                    <div class="col-sm-4 portfolio-item">
                        <a href="https://robustahealth.com" class="portfolio-link" data-toggle="modal">
                            <div class="caption">
                                <div class="container" width="100%">
                                    <img src="https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/robustahealth_shop.jpg" alt="robusta_health">
                                </div>
                            </div>
                            <%= image_tag("https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/robustahealth_home.jpg")%><!--img src="img/portfolio/game.png"--><class="img-responsive" alt="solucent_home">
                    </div>
                    <div class="col-sm-4 portfolio-item">
                        <a href="http://jamecapital.com" class="portfolio-link" data-toggle="modal">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <%=image_tag("https://s3.us-east-2.amazonaws.com/danieljohnportfolio2/jamecapnew.png")%><!--img src="img/portfolio/cabin.png"--><class="img-responsive" alt="Gentlemen Of York">
                        </a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="col-sm-2 offset-3">           
        <div class="container">
            <div class="col-sm-12">
                <h4>Recent Articles</h4>
                    <% @articles.each do |a| %>
                    Created by: <%= a.user.username %><br/>
                    <strong><%= link_to a.title, a %></strong>
                    <p><%= truncate(a.body) %></p>
                    <% end %>
            </div>    
        </div>
    </section> 